#!/bin/bash

while true
do

# Logo

echo "========================================================================================================================"
curl -s https://raw.githubusercontent.com/nodersteam/script/main/Noders.sh | bash
echo "========================================================================================================================"

sleep 2

# Menu

PS3='Select an action: '
options=("Set the required variables" "Build" "Run" "Check log GateWay" "Check log Client" "Check log Requester" "Exit")
select opt in "${options[@]}"
               do
                   case $opt in                           

"Set the required variables")
echo "============================================================"
echo "Install start"
echo "============================================================"

# set vars

echo "============================================================"
echo "Setup GateWay Name:"
echo "============================================================"
read GATEWAYNAME
echo "============================================================"
echo "Setup Wallet address:"
echo "============================================================"
read WALLETADDRESS
echo "============================================================"
echo "Setup Mnemonic for wallet:"
echo "============================================================"
read MNEMONIC
echo "============================================================"
echo "Setup Client name:"
echo "============================================================"
read CLIENTNAME

sudo dpkg --configure -a \
sudo apt install ufw make clang pkg-config libssl-dev build-essential git -y -qq \
sudo curl https://sh.rustup.rs -sSf | sh -s -- -y \
source $HOME/.cargo/env \
cd $HOME

ufw version
sudo apt install ufw -y
sudo ufw enable
sudo ufw status
sudo ufw allow 1789,22,9000/tcp

break
;;

"Build")                 
cd $HOME
git clone https://github.com/nymtech/nym.git
cd nym
git reset --hard
git pull
git checkout tags/v1.1.3

cargo build -p nym-gateway --release
cargo build -p nym-client --release
cargo build -p nym-network-requester --release

sudo mv $HOME/nym/target/release/nym-gateway /usr/local/bin/
sudo mv $HOME/nym/target/release/nym-client /usr/local/bin/
sudo mv $HOME/nym/target/release/nym-network-requester /usr/local/bin/

break
;;   

"Run")

nym-gateway init --id $GATEWAYNAME --host $(curl ifconfig.me) --wallet-address $WALLETADDRESS --mnemonic "$MNEMONIC"

sudo tee <<EOF >/dev/null /etc/systemd/journald.conf
Storage=persistent
EOF

sudo systemctl restart systemd-journald

sudo tee <<EOF >/dev/null /etc/systemd/system/nym-gateway.service
[Unit]
Description=Nym GateWay

[Service]
User=$USER
ExecStart=/usr/local/bin/nym-gateway run --id $GATEWAYNAME
KillSignal=SIGINT
Restart=on-failure
RestartSec=30
StartLimitInterval=350
StartLimitBurst=10
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

nym-client init --id $CLIENTNAME

sudo tee <<EOF >/dev/null /etc/systemd/system/nym-client.service
[Unit]
Description=Nym Client (1.1.3)
StartLimitInterval=350
StartLimitBurst=10

[Service]
User=root 
LimitNOFILE=65536
ExecStart=/usr/local/bin/nym-client run --id $CLIENTNAME
KillSignal=SIGINT
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF

sudo tee <<EOF >/dev/null /etc/systemd/system/nym-network-requester.service
[Unit]
Description=Nym Client (1.1.3)
StartLimitInterval=350
StartLimitBurst=10

[Service]
User=root 
LimitNOFILE=65536
ExecStart=/usr/local/bin/nym-network-requester run
KillSignal=SIGINT
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF

echo "DefaultLimitNOFILE=65535" >> /etc/systemd/system.conf

sed -i.def "s|validator_api_urls.*|validator_api_urls = [\
	'https://validator.nymtech.net/api/'|" $HOME/.nym/mixnodes/*/config/config.toml
sudo tee <<EOF >/dev/null /etc/systemd/journald.conf

systemctl daemon-reload
service nym-gateway start
service nym-client start
service nym-network-requester start

break
;;

"Check log GateWay")

journalctl -u nym-gateway -f -o cat

break
;;

"Check log Client")

journalctl -u nym-gateway -f -o cat

break
;;

"Check log Requester")

journalctl -u nym-gateway -f -o cat

break
;;

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
